# Generated by Django 4.0.5 on 2022-06-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationtimestamp', models.DateTimeField(auto_created=True)),
                ('modificationtimestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField(max_length=1000)),
                ('body', models.TextField()),
            ],
        ),
    ]
