# Generated by Django 4.0.5 on 2022-06-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['creationtimestamp']},
        ),
        migrations.AlterField(
            model_name='post',
            name='creationtimestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='modificationtimestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
